import Head from 'next/head';
import { Inter } from 'next/font/google';
import { gql, useQuery } from '@apollo/client';
import { useState } from 'react';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

const GET_ANIME = gql`
  query ($id: Int, $page: Int, $perPage: Int) {
    Page(page: $page, perPage: $perPage) {
      pageInfo {
        total
        currentPage
        lastPage
        hasNextPage
        perPage
      }
      # Define which variables will be used in the query (id)
      media(id: $id, type: ANIME) {
        # Insert our variables into the query arguments (id) (type: ANIME is hard-coded in the query)
        id
        title {
          english
        }
        coverImage {
          large
        }
      }
    }
  }
`;

export default function Home() {
  const [page, setPage] = useState(1);

  const anime = useQuery(GET_ANIME, {
    variables: {
      page,
      perPage: 10,
    },
  });

  function handlePagination(type: 'PREV' | 'NEXT') {
    if (type === 'PREV' && page > 1) {
      setPage(page - 1);
    } else if (type === 'NEXT' && anime.data.Page.pageInfo.hasNextPage) {
      setPage(page + 1);
    }
  }

  if (anime.loading) {
    return <p>Loading...</p>;
  }

  if (anime.error) {
    return <p>Error!!</p>;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        {anime.data.Page.media.map(((m: any) => (
          <div key={m.id}>
            <Image src={m.coverImage.large} alt={m.title.english} width={100} height={100} />
            <p>{m.title.english}</p>
          </div>
        )))}
        <button onClick={() => handlePagination('PREV')}>prev</button>
        <button onClick={() => handlePagination('NEXT')}>next</button>
      </main>
    </>
  );
}
