import { GET_ANIME_LIST } from '@/graphql/anime';
import { useQuery } from '@apollo/client';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [page, setPage] = useState(1);

  const anime = useQuery(GET_ANIME_LIST, {
    variables: {
      page,
      perPage: 10,
    },
  });

  function handlePagination(type: 'PREV' | 'NEXT') {
    if (type === 'PREV' && page > 1) {
      setPage(page - 1);
    } else if (type === 'NEXT' && anime.data?.Page?.pageInfo?.hasNextPage) {
      setPage(page + 1);
    }
  }

  if (anime.loading) {
    return <p>Loading...</p>;
  }

  if (anime.error) {
    return <p>Error!!</p>;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        {anime.data?.Page?.media?.map((m) => (
          <Link key={m?.id} href={`/anime/${m?.id}`}>
            <Image
              src={m?.coverImage?.large || ''}
              alt={m?.title?.english || ''}
              width={100}
              height={100}
            />
            <p>{m?.title?.english}</p>
          </Link>
        ))}
        <button onClick={() => handlePagination('PREV')}>prev</button>
        <button onClick={() => handlePagination('NEXT')}>next</button>
      </main>
    </>
  );
}
